server:
  port: 9004
spring:
  application:
    name: ORDER-SERVICE
  datasource:
    username: thujitha
    password: *
    url: jdbc:mysql://localhost:3306/orderDB
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
